version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-custom-network

  api:
    build:
      context: ./api
    container_name: api_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha123
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-custom-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - my-custom-network

volumes:
  db_data:

networks:
  my-custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16